import type { CareerLevel } from "@/lib/types";

export const CAREER_LEVELS: CareerLevel[] = [
  {
    id: "foundation",
    name: "Foundation",
    shortLabel: "L0",
    metaShortLabel: "E3",
    description: "Syntax fluency — learn the chunks before retrieval pressure",
    characteristics: "Syntax fluency, visible code, low pressure",
    fluencyLevelRange: [1, 2],
    complexity: 1,
    pressureMultiplier: 0.6,
    preferredRecallMode: "full-copy",
    sprintThresholdAdjust: -8,
    difficultyFilter: ["easy"],
  },
  {
    id: "junior",
    name: "Junior",
    shortLabel: "L3",
    metaShortLabel: "E3",
    description: "Implementation consistency — token recall and rhythm",
    characteristics: "Implementation consistency, token recall",
    fluencyLevelRange: [2, 3],
    complexity: 2,
    pressureMultiplier: 0.75,
    preferredRecallMode: "token-blank",
    sprintThresholdAdjust: -4,
    difficultyFilter: ["easy", "medium"],
  },
  {
    id: "mid",
    name: "Mid",
    shortLabel: "L4",
    metaShortLabel: "E4",
    description: "Balanced retrieval — line recall and spaced resurfacing",
    characteristics: "Balanced retrieval, pattern breadth",
    fluencyLevelRange: [2, 4],
    complexity: 3,
    pressureMultiplier: 1,
    preferredRecallMode: "line-blank",
    sprintThresholdAdjust: 0,
    difficultyFilter: ["easy", "medium", "hard"],
  },
  {
    id: "senior",
    name: "Senior",
    shortLabel: "L5",
    metaShortLabel: "E5",
    description: "Systems decomposition — skeleton recall and sprint pressure",
    characteristics: "Systems decomposition, sprint pressure",
    fluencyLevelRange: [3, 5],
    complexity: 4,
    pressureMultiplier: 1.25,
    preferredRecallMode: "skeleton",
    sprintThresholdAdjust: 4,
    difficultyFilter: ["medium", "hard"],
  },
  {
    id: "staff",
    name: "Staff",
    shortLabel: "L6",
    metaShortLabel: "E6",
    description: "Architectural reasoning — hard motifs under time pressure",
    characteristics: "Architectural reasoning, hard motifs",
    fluencyLevelRange: [4, 5],
    complexity: 5,
    pressureMultiplier: 1.4,
    preferredRecallMode: "skeleton",
    sprintThresholdAdjust: 6,
    difficultyFilter: ["medium", "hard"],
  },
  {
    id: "research",
    name: "Research",
    shortLabel: "L7+",
    metaShortLabel: "E6+",
    description: "ML/scientific motifs — optimization and tensor fluency",
    characteristics: "ML/scientific motifs, advanced abstraction",
    fluencyLevelRange: [4, 5],
    complexity: 5,
    pressureMultiplier: 1.2,
    preferredRecallMode: "line-blank",
    sprintThresholdAdjust: 3,
    difficultyFilter: ["medium", "hard"],
  },
];

export function getCareerLevel(id: string): CareerLevel {
  return CAREER_LEVELS.find((l) => l.id === id) ?? CAREER_LEVELS[2];
}
