import type { CompanyTrack, SprintGradingProfile } from "@/lib/types";

const DEFAULT_SPRINT: SprintGradingProfile = {
  targetWpm: 40,
  minAccuracy: 88,
  speedWeight: 0.3,
  accuracyWeight: 0.45,
  hesitationPenaltyFactor: 3,
  readinessThresholds: { ready: 85, strong: 72, developing: 58 },
  gradeLabels: {
    ready: "Implementation ready",
    strong: "Strong under pressure",
    developing: "Developing",
  },
};

export const COMPANY_TRACKS: CompanyTrack[] = [
  {
    id: "general",
    name: "General Fluency",
    tagline: "Balanced procedural training across all patterns",
    marketingLabel: "Company-specific implementation fluency",
    cognitiveProfile: "Breadth-first syntax fluency without company bias",
    status: "active",
    languages: ["python", "javascript", "java", "cpp"],
    motifWeights: {},
    patternWeights: {},
    difficultyBias: { easy: 1, medium: 1, hard: 1 },
    modeWeights: { type: 0.3, recall: 0.3, review: 0.2, sprint: 0.2 },
    sprintProfile: DEFAULT_SPRINT,
    coaching: {
      sprintEmphasis: "Build consistent implementation reflexes",
      weaknessFraming: "Reinforce the weak motif before advancing",
      strengthFraming: "Solid execution — push the next pattern",
      nextStepPrefix: "Next drill",
    },
  },
  {
    id: "meta",
    name: "Meta Fluency",
    tagline: "Speed + graphs + implementation tempo",
    marketingLabel: "Meta-style implementation fluency",
    cognitiveProfile: "High-speed graph traversal, queue/stack reflexes, execution under pressure",
    status: "active",
    languages: ["python"],
    packId: "company-meta",
    motifWeights: {
      "bfs-queue": 2.2,
      "dfs-recursion": 2,
      "graph-adjacency": 2,
      "heap-push-pop": 1.5,
      "sliding-window-expand": 1.4,
      "hash-set-membership": 1.3,
    },
    patternWeights: {
      graphs: 2.2,
      "dfs-bfs": 2,
      "sliding-window": 1.5,
      "hash-map": 1.3,
      heap: 1.2,
    },
    difficultyBias: { easy: 0.7, medium: 1.3, hard: 1.1 },
    modeWeights: { type: 0.2, recall: 0.25, review: 0.1, sprint: 0.45 },
    sprintProfile: {
      targetWpm: 48,
      minAccuracy: 86,
      speedWeight: 0.42,
      accuracyWeight: 0.38,
      hesitationPenaltyFactor: 3.5,
      readinessThresholds: { ready: 82, strong: 68, developing: 55 },
      gradeLabels: {
        ready: "Tempo-ready",
        strong: "Strong sprint tempo",
        developing: "Build graph speed",
      },
    },
    coaching: {
      sprintEmphasis: "Meta optimizes for speed under graph pressure — Sprint-heavy",
      weaknessFraming: "Slow boundary on graph syntax — one tempo rep",
      strengthFraming: "Clean tempo — push a harder graph motif",
      nextStepPrefix: "Speed drill",
    },
  },
  {
    id: "google",
    name: "Google Fluency",
    tagline: "Breadth + correctness + edge-case handling",
    marketingLabel: "Google-style implementation fluency",
    cognitiveProfile: "Broad algorithm coverage, readable implementation, edge-case discipline",
    status: "active",
    languages: ["python"],
    packId: "company-google",
    motifWeights: {
      "binary-search-mid": 1.8,
      "binary-search-boundary": 1.8,
      "tree-recursion": 1.7,
      "dp-tabulation": 1.6,
      "two-pointer-converge": 1.5,
      "prefix-sum": 1.4,
    },
    patternWeights: {
      "binary-search": 1.8,
      trees: 1.7,
      "dynamic-programming": 1.6,
      "two-pointers": 1.5,
      arrays: 1.4,
      "hash-map": 1.3,
    },
    difficultyBias: { easy: 1, medium: 1.2, hard: 1.1 },
    modeWeights: { type: 0.25, recall: 0.3, review: 0.25, sprint: 0.2 },
    sprintProfile: {
      targetWpm: 38,
      minAccuracy: 92,
      speedWeight: 0.22,
      accuracyWeight: 0.52,
      hesitationPenaltyFactor: 2.5,
      readinessThresholds: { ready: 88, strong: 75, developing: 60 },
      gradeLabels: {
        ready: "Correctness-ready",
        strong: "Consistent implementation",
        developing: "Tighten edge cases",
      },
    },
    coaching: {
      sprintEmphasis: "Google weights correctness over raw speed — balanced modes",
      weaknessFraming: "Edge-case syntax slipped — review then retry",
      strengthFraming: "Clean, readable execution — broaden to next pattern",
      nextStepPrefix: "Breadth drill",
    },
  },
  {
    id: "openai",
    name: "OpenAI Fluency",
    tagline: "Systems + ML + backend Python",
    marketingLabel: "OpenAI-style implementation fluency",
    cognitiveProfile: "Python backend fluency, async patterns, tensor ops, systems motifs",
    status: "active",
    languages: ["python"],
    packId: "company-openai",
    motifWeights: {
      "counter-defaultdict": 1.6,
      "hash-lookup": 1.5,
      "graph-adjacency": 1.4,
      "deque-window": 1.3,
      "prefix-sum": 1.3,
    },
    patternWeights: {
      "hash-map": 1.6,
      graphs: 1.4,
      stack: 1.3,
      "dynamic-programming": 1.2,
    },
    difficultyBias: { easy: 0.9, medium: 1.3, hard: 1.2 },
    modeWeights: { type: 0.25, recall: 0.35, review: 0.2, sprint: 0.2 },
    sprintProfile: {
      targetWpm: 36,
      minAccuracy: 90,
      speedWeight: 0.25,
      accuracyWeight: 0.48,
      hesitationPenaltyFactor: 2.8,
      readinessThresholds: { ready: 84, strong: 70, developing: 56 },
      gradeLabels: {
        ready: "Backend-ready",
        strong: "Systems fluency building",
        developing: "Drill API chunks",
      },
    },
    coaching: {
      sprintEmphasis: "Systems + ML backend — recall-heavy for API chunk retrieval",
      weaknessFraming: "Backend API chunk needs retrieval strength",
      strengthFraming: "Strong Python backend reflex — add systems motif",
      nextStepPrefix: "Systems drill",
    },
  },
  {
    id: "anthropic",
    name: "Anthropic Fluency",
    tagline: "Python + backend + ML infra + clarity",
    marketingLabel: "Anthropic-style implementation fluency",
    cognitiveProfile: "Readable Python, backend systems, ML infra, reasoning clarity",
    status: "active",
    languages: ["python"],
    packId: "company-anthropic",
    motifWeights: {
      "counter-defaultdict": 1.5,
      "hash-lookup": 1.5,
      "bfs-queue": 1.4,
      "dp-memoization": 1.4,
      "graph-adjacency": 1.3,
    },
    patternWeights: {
      "hash-map": 1.5,
      graphs: 1.4,
      "dynamic-programming": 1.3,
      "dfs-bfs": 1.3,
    },
    difficultyBias: { easy: 1, medium: 1.25, hard: 1.15 },
    modeWeights: { type: 0.22, recall: 0.33, review: 0.25, sprint: 0.2 },
    sprintProfile: {
      targetWpm: 35,
      minAccuracy: 91,
      speedWeight: 0.2,
      accuracyWeight: 0.5,
      hesitationPenaltyFactor: 2.6,
      readinessThresholds: { ready: 86, strong: 73, developing: 58 },
      gradeLabels: {
        ready: "Infra-ready",
        strong: "Clear implementation",
        developing: "Sharpen readability",
      },
    },
    coaching: {
      sprintEmphasis: "Clarity + ML infra — review mode for reasoning consolidation",
      weaknessFraming: "Reasoning clarity dipped — review motif, then recall",
      strengthFraming: "Clear, precise code — push ML infra patterns",
      nextStepPrefix: "Clarity drill",
    },
  },
  {
    id: "deepmind",
    name: "DeepMind Fluency",
    tagline: "Algorithms + ML + scientific computing",
    marketingLabel: "DeepMind-style implementation fluency",
    cognitiveProfile: "Algorithm breadth, tensor reasoning, optimization, scientific Python",
    status: "active",
    languages: ["python"],
    packId: "company-deepmind",
    motifWeights: {
      "dp-tabulation": 1.8,
      "dp-memoization": 1.7,
      "binary-search-answer": 1.6,
      "graph-adjacency": 1.5,
      "heap-push-pop": 1.4,
      "prefix-sum": 1.4,
    },
    patternWeights: {
      "dynamic-programming": 1.8,
      "binary-search": 1.6,
      graphs: 1.5,
      heap: 1.3,
      arrays: 1.2,
    },
    difficultyBias: { easy: 0.8, medium: 1.2, hard: 1.4 },
    modeWeights: { type: 0.2, recall: 0.35, review: 0.2, sprint: 0.25 },
    sprintProfile: {
      targetWpm: 37,
      minAccuracy: 89,
      speedWeight: 0.28,
      accuracyWeight: 0.44,
      hesitationPenaltyFactor: 3,
      readinessThresholds: { ready: 83, strong: 70, developing: 55 },
      gradeLabels: {
        ready: "Research-ready",
        strong: "Algorithm + ML fluency",
        developing: "Build optimization reflexes",
      },
    },
    coaching: {
      sprintEmphasis: "Algorithms + scientific computing — hard snippets at senior+",
      weaknessFraming: "Optimization motif needs reinforcement",
      strengthFraming: "Strong algorithmic reflex — advance complexity",
      nextStepPrefix: "Research drill",
    },
  },
  {
    id: "jane-street",
    name: "Jane Street Fluency",
    tagline: "Probability + optimization + precision",
    marketingLabel: "Quant-style implementation fluency",
    cognitiveProfile: "Mathematical reasoning, combinatorics, tight implementation precision",
    status: "planned",
    languages: ["python"],
    packId: "company-jane-street",
    motifWeights: {
      "dp-tabulation": 1.7,
      "greedy-local": 1.6,
      "prefix-sum": 1.5,
      "binary-search-answer": 1.5,
      "heap-push-pop": 1.4,
    },
    patternWeights: {
      "dynamic-programming": 1.7,
      heap: 1.5,
      "binary-search": 1.5,
      arrays: 1.4,
    },
    difficultyBias: { easy: 0.6, medium: 1.2, hard: 1.5 },
    modeWeights: { type: 0.15, recall: 0.35, review: 0.15, sprint: 0.35 },
    sprintProfile: {
      targetWpm: 42,
      minAccuracy: 93,
      speedWeight: 0.35,
      accuracyWeight: 0.48,
      hesitationPenaltyFactor: 4,
      readinessThresholds: { ready: 87, strong: 74, developing: 60 },
      gradeLabels: {
        ready: "Precision-ready",
        strong: "Quant tempo building",
        developing: "Drill math motifs",
      },
    },
    coaching: {
      sprintEmphasis: "Precision under pressure — math + optimization motifs",
      weaknessFraming: "Precision slipped on math boundary — retry clean",
      strengthFraming: "Tight implementation — push optimization motif",
      nextStepPrefix: "Precision drill",
    },
  },
];

export function getCompanyTrack(id: string): CompanyTrack {
  return COMPANY_TRACKS.find((t) => t.id === id) ?? COMPANY_TRACKS[0];
}

export function activeCompanyTracks(): CompanyTrack[] {
  return COMPANY_TRACKS.filter((t) => t.status === "active" && t.id !== "general");
}
